name: Sync Image to Aliyun
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    # 添加步骤来执行skopeo命令，从docker.io仓库拉取镜像，并将其推送到阿里云个人仓库。
    steps:
    - name: Git pull
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-bj2nh5ymscjs3556.cn-beijing.personal.cr.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false
 
    # 使用shell命令批量同步所需的镜像到阿里云个人仓库中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
        skopeo copy docker://docker.io/userxy2015/ngnix:latest docker://crpi-bj2nh5ymscjs3556.cn-beijing.personal.cr.aliyuncs.com/prisms/ngnix:latest
